spring:
#  profiles:
#    active: local
  application:
    name: astro-data-storage

datasource:
  url: ${HOST}
  username: ${USER}
  password: ${PASSWORD}
  driver-class-name: org.postgresql.Driver
  hikari:
    initialization-fail-timeout: -1
    connection-timeout: 30000
    validation-timeout: 5000
    minimum-idle: 5
    maximum-pool-size: 20

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: ${JPA_VIEW_MODE}

server:
  servlet:
    context-path: /astro-data
  port: 8080